## identify policy atance 

#%%
from pathlib import Path
from typing import List
import pandas as pd

def _standardize_type_column(df: pd.DataFrame) -> pd.DataFrame:
    """Recode type values: staff_a -> staff, buff_a -> buff (in-place)."""
    if "type" not in df.columns:
        raise ValueError("Column 'type' not found in input CSV")

    df = df.copy()
    df["type"] = (
        df["type"].replace({"staff_a": "staff", "buff_a": "buff"}).fillna(df["type"])  # type: ignore[assignment]
    )
    return df


def _aggregate_to_document_by_type(df: pd.DataFrame) -> pd.DataFrame:
    """
    For each document (Print ISBN), then for each type within that doc, and for each topic dummy column:
      - collect all text where the dummy == 1
      - concatenate paragraphs with double newlines
      - append one row: (Print ISBN, type, topic, text)
    Returns a document-level DataFrame with columns: Print ISBN, type, topic, text
    """
    # Validate required columns
    for col in ["Print ISBN", "type", "text"]:
        if col not in df.columns:
            raise ValueError(f"Column '{col}' not found in input DataFrame")

    # Identify topic dummy columns dynamically
    topic_dummy_cols: List[str] = [c for c in df.columns if c.endswith("_dummy")]
    if not topic_dummy_cols:
        raise ValueError("No topic dummy columns (ending with '_dummy') were found in input DataFrame")

    out_rows = []

    # Loop: document -> type -> topic
    for isbn in df["Print ISBN"].astype(str).unique():
        df_doc = df[df["Print ISBN"].astype(str) == isbn]

        for typ in df_doc["type"].astype(str).unique():
            df_doc_type = df_doc[df_doc["type"].astype(str) == typ]

            for col in topic_dummy_cols:
                # robustly treat dummy as 0/1 (or bool); select rows where it's "on"
                mask = pd.to_numeric(df_doc_type[col], errors="coerce").fillna(0).astype(int) == 1
                texts = df_doc_type.loc[mask, "text"].dropna().astype(str)
                texts = [t for t in texts if t.strip()]  # drop empty/whitespace-only

                if not texts:
                    continue

                out_rows.append({
                    "Print ISBN": isbn,
                    "type": typ,
                    "topic": col[:-6],           # remove "_dummy"
                    "text": "\n\n".join(texts),  # keep paragraph order as in df
                })

    # If nothing matched, return empty frame with expected columns
    if not out_rows:
        return pd.DataFrame(columns=["Print ISBN", "type", "topic", "text"])

    return pd.DataFrame(out_rows, columns=["Print ISBN", "type", "topic", "text"])


def parse_args(argv=None):
    import argparse

    parser = argparse.ArgumentParser(description="Aggregate paragraph-level topic dummies to document-level by type")
    parser.add_argument(
        "--input-csv",
        type=str,
        default="/data/home/xiong/data/Fund/CSR/Tractions/output/paragraph_with_sector_batch.csv",
        help="Path to paragraph-level CSV with topic dummy columns",
    )
    parser.add_argument(
        "--output-csv",
        type=str,
        default="/data/home/xiong/data/Fund/CSR/Tractions/output/document_by_type_sector.csv",
        help="Path to write aggregated document-level CSV",
    )
    parser.add_argument(
        '--metafile', 
        type=str, 
        default='/data/home/xiong/data/Fund/CSR/Tractions/ArticleIV_xml_updated/IMF_Main_MetaData_20240710_toRan_filtered.xlsx',
        help="Path to metadata file",
    )
    return parser.parse_args(argv)


#%%
if __name__ == "__main__":
    #### for now, just use results previous generated by xiaorui , will veryfy and update latter 
    args = parse_args(['--input-csv', '/data/home/xiong/data/Fund/CSR/Traction/output/df_paragraphs_type_topics.csv',
                       '--output-csv', '/data/home/xiong/data/Fund/CSR/Tractions/output/document_by_type_sector.csv',
                       '--metafile', '/data/home/xiong/data/Fund/CSR/Tractions/ArticleIV_xml_updated/IMF_Main_MetaData_20240710_toRan_filtered.xlsx'])

    input_path = Path(args.input_csv)
    output_path = Path(args.output_csv)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Load, recode, aggregate
    df = pd.read_csv(input_path)
    df = _standardize_type_column(df)
    agg_df = _aggregate_to_document_by_type(df)

    meta_df = pd.read_excel(args.metafile)
    keep_cols = ['Print ISBN','Primary Country Code', 'Primary Country Description','Year from title']
    meta_df = meta_df[keep_cols]
    # Ensure matching dtypes for merge key 'Print ISBN'
    # Coerce to numeric first (to drop any stray decimals) then to pandas nullable Int and finally to string
    agg_df['Print ISBN'] = pd.to_numeric(agg_df['Print ISBN'], errors='coerce').astype('Int64').astype(str)
    meta_df['Print ISBN'] = pd.to_numeric(meta_df['Print ISBN'], errors='coerce').astype('Int64').astype(str)
    agg_df_merged = agg_df.merge(meta_df, on='Print ISBN', how='left')
    # Rename columns for consistency
    agg_df_merged = agg_df_merged.rename(columns={
        'Primary Country Code': 'country_code',
        'Primary Country Description': 'country',
        'Year from title': 'year'
    })
    #### need to double check in the end 
    # # Show records where Primary Country Description is NA
    # na_records = agg_df_merged[agg_df_merged['Primary Country Description'].isna()]
    # if len(na_records) > 0:
    #     print(f"\nFound {len(na_records)} records with missing Primary Country Description:")
    #     print(na_records[['Print ISBN', 'Title', 'Primary Country Code', 'Primary Country Description', 'Year from title']].to_string())
    # else:
    #     print("\nNo records found with missing Primary Country Description")
    
    # Save
    agg_df_merged.to_csv(output_path, index=False)
    print(f"Wrote aggregated document-level data to {output_path}")


# %%
